# Generated by Django 2.1.1 on 2018-11-10 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description_file_post', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_files', models.CharField(max_length=140)),
                ('description_subject', models.TextField()),
                ('url', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='filepost',
            name='subject_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_file_post', to='file.SubjectFiles'),
        ),
    ]
