# Generated by Django 2.1.1 on 2018-11-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectfiles',
            old_name='url',
            new_name='slug',
        ),
    ]
