# Generated by Django 2.1.2 on 2018-11-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
