# Generated by Django 2.1.2 on 2018-11-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20181108_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subjectfiles',
            name='author',
        ),
    ]
