# Generated by Django 2.1.2 on 2018-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20181108_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
