
version: '2'

services:

    web:

        build: .
        # image: docker-hub.io/LOGIN # docker-compose push
        working_dir: /src
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
              
